/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userValidation = require('./user.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.dealValidation = require('./deal.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.dealNotesValidation = require('./dealNotes.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.lenderProgramValidation = require('./lenderProgram.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.lendingInstitutionValidation = require('./lendingInstitution.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.lenderPlacementValidation = require('./lenderPlacement.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.lenderContactValidation = require('./lenderContact.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.emailTemplateValidation = require('./emailTemplate.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.activityLogValidation = require('./activityLog.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.taskValidation = require('./task.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.dealDocumentValidation = require('./dealDocument.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.authValidation = require('./auth.validation');

module.exports.lenderNotesValidation = require('./lenderNotes.validation');

module.exports.feedbackValidation = require('./feedback.validation');

module.exports.bugReportValidation = require('./bugReport.validation');

module.exports.FAQValidation = require('./FAQ.validation');

module.exports.lenderInstituteNotesValidation = require('./lenderInstituteNotes.validation');
