version: 0.0
os: linux
files:
  - source: /
    destination: /opt/kobal-kapital-backend
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 3000
      runas: ubuntu
