/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.s3Controller = require('./s3.controller');
module.exports.searchController = require('./search.controller');
module.exports.ratesController = require('./rates.controller');
module.exports.authController = require('./auth.controller');
module.exports.importFileController = require('./importFile.controller');
module.exports.exportDBController = require('./exportDB.controller');
module.exports.wehbookController = require('./wehbook.controller');
