/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { BugReport } from 'models';

// eslint-disable-next-line import/prefer-default-export
export async function createBugReport(body) {
  return BugReport.create(body);
}
