/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { DealDocument } from 'models';

export async function getDealDocumentById(id, options = {}) {
  const dealDocument = await DealDocument.findById(id, options.projection, options);
  return dealDocument;
}

export async function getOne(query, options = {}) {
  const dealDocument = await DealDocument.findOne(query, options.projection, options);
  return dealDocument;
}

export async function getDealDocumentList(filter, options = {}) {
  const dealDocument = await DealDocument.find(filter, options.projection, options);
  return dealDocument;
}

export async function getDealDocumentListWithPagination(filter, options = {}) {
  const dealDocument = await DealDocument.paginate(filter, options);
  return dealDocument;
}

export async function createDealDocument(body) {
  const dealDocument = await DealDocument.create(body);
  return dealDocument;
}

export async function updateDealDocument(filter, body, options = {}) {
  const dealDocument = await DealDocument.findOneAndUpdate(filter, body, options);
  return dealDocument;
}

export async function updateManyDealDocument(filter, body, options = {}) {
  const dealDocument = await DealDocument.updateMany(filter, body, options);
  return dealDocument;
}

export async function removeDealDocument(filter) {
  const dealDocument = await DealDocument.findOneAndRemove(filter);
  return dealDocument;
}

export async function removeManyDealDocument(filter) {
  const dealDocument = await DealDocument.deleteMany(filter);
  return dealDocument;
}
