/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userService = require('./user.service');
module.exports.dealService = require('./deal.service');
module.exports.invitationService = require('./invitation.service');
module.exports.dealNotesService = require('./dealNotes.service');
module.exports.lenderProgramService = require('./lenderProgram.service');
module.exports.lendingInstitutionService = require('./lendingInstitution.service');
module.exports.lenderPlacementService = require('./lenderPlacement.service');
module.exports.lenderContactService = require('./lenderContact.service');
module.exports.emailTemplateService = require('./emailTemplate.service');
module.exports.activityLogService = require('./activityLog.service');
module.exports.taskService = require('./task.service');
module.exports.dealDocumentService = require('./dealDocument.service');
module.exports.authService = require('./auth.service');
module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
module.exports.passportService = require('./passport.service');
module.exports.s3Service = require('./s3.service');
module.exports.temps3CronService = require('./temps3Cron.service');
module.exports.notificationService = require('./notification.service');
module.exports.queueService = require('./queue.service');
module.exports.lenderNotesService = require('./lenderNotes.service');
