/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Deal, Invitation } from 'models';

export async function getInvitationById(id, options = {}) {
  const invitation = await Invitation.findById(id, options.projection, options);
  return invitation;
}

export async function getOne(query, options = {}) {
  const invitation = await Invitation.findOne(query, options.projection, options);
  return invitation;
}

export async function getInvitationList(filter, options = {}) {
  const invitation = await Invitation.find(filter, options.projection, options);
  return invitation;
}

export async function getInvitationListWithPagination(filter, options = {}) {
  const invitation = await Invitation.paginate(filter, options);
  return invitation;
}

export async function createInvitation(body) {
  if (body.deal) {
    const deal = await Deal.findOne({ _id: body.deal });
    if (!deal) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field deal is not valid');
    }
  }
  const invitation = await Invitation.create(body);
  return invitation;
}

export async function updateInvitation(filter, body, options = {}) {
  if (body.deal) {
    const deal = await Deal.findOne({ _id: body.deal });
    if (!deal) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field deal is not valid');
    }
  }
  const invitation = await Invitation.findOneAndUpdate(filter, body, options);
  return invitation;
}

export async function updateManyInvitation(filter, body, options = {}) {
  const invitation = await Invitation.updateMany(filter, body, options);
  return invitation;
}

export async function removeInvitation(filter) {
  const invitation = await Invitation.findOneAndRemove(filter);
  return invitation;
}

export async function removeManyInvitation(filter) {
  const invitation = await Invitation.deleteMany(filter);
  return invitation;
}
