/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { Task } from 'models';

export async function getTaskById(id, options = {}) {
  const task = await Task.findById(id, options.projection, options);
  return task;
}

export async function getOne(query, options = {}) {
  const task = await Task.findOne(query, options.projection, options);
  return task;
}

export async function getTaskList(filter, options = {}) {
  const task = await Task.find(filter, options.projection, options);
  return task;
}

export async function getTaskListWithPagination(filter, options = {}) {
  const task = await Task.paginate(filter, options);
  return task;
}

export async function createTask(body, options = {}) {
  const task = await Task.create(body);
  return task;
}

export async function updateTask(filter, body, options = {}) {
  const task = await Task.findOneAndUpdate(filter, body, options);
  return task;
}

export async function updateManyTask(filter, body, options = {}) {
  const task = await Task.updateMany(filter, body, options);
  return task;
}

export async function removeTask(filter) {
  const task = await Task.findOneAndRemove(filter);
  return task;
}

export async function removeManyTask(filter) {
  const task = await Task.deleteMany(filter);
  return task;
}
