/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userController = require('./user.controller');
module.exports.dealController = require('./deal.controller');
module.exports.dealNotesController = require('./dealNotes.controller');
module.exports.lenderProgramController = require('./lenderProgram.controller');
module.exports.lendingInstitutionController = require('./lendingInstitution.controller');
module.exports.lenderPlacementController = require('./lenderPlacement.controller');
module.exports.lenderContactController = require('./lenderContact.controller');
module.exports.emailTemplateController = require('./emailTemplate.controller');
module.exports.activityLogController = require('./activityLog.controller');
module.exports.feedbackController = require('./feedback.controller');
module.exports.bugReportController = require('./bugReport.controller');
module.exports.lenderInstituteNotesController = require('./lenderInstituteNotes.controller');
module.exports.FAQController = require('./FAQ.controller');
module.exports.taskController = require('./task.controller');
module.exports.dealDocumentController = require('./dealDocument.controller');
module.exports.authController = require('./auth.controller');
module.exports.lenderNotesController = require('./lenderNotes.controller');
module.exports.notificationController = require('./notification.controller');
module.exports.dealSummaryController = require('./dealSummary.controller');
