/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.captchaValidation = require('./captcha.validation');
module.exports.s3Validation = require('./s3.validation');
module.exports.searchValidation = require('./search.validation');
module.exports.authValidation = require('./auth.validation');
