/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const documentSchema = new mongoose.Schema(
  {
    url: {
      type: String,
      required: true,
    },
    fileName: {
      type: String,
      required: true,
    },
    documentType: {
      type: String,
      enum: Object.values(enumModel.EnumDocumentTypeOfDealDocument),
      required: true,
      default: enumModel.EnumDocumentTypeOfDealDocument.OTHERS,
    },
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);
const DealDocumentSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    documents: {
      type: [documentSchema],
    },
    deal: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Deal',
      required: true,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true }, autoCreate: true }
);
DealDocumentSchema.plugin(toJSON);
DealDocumentSchema.plugin(mongoosePaginateV2);
DealDocumentSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const DealDocumentModel = mongoose.models.DealDocument || mongoose.model('DealDocument', DealDocumentSchema, 'DealDocument');
module.exports = DealDocumentModel;
