/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose, { Schema } from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';
import enumModel from './enum.model';

const PhotosSchema = new mongoose.Schema({
  url: {
    type: String,
  },
  fileName: {
    type: String,
  },
});

// heading schema as in the heading we need dealName, city, state, info: asset type, loan type, loan amount etc.
const headingSchema = new mongoose.Schema({
  dealName: {
    type: String,
  },
  cityState: {
    type: String,
  },
  dealInfo: {
    type: String,
  },
});

/**
 * The 'key' field represents the name or identifier of the dynamic field.
 * The 'value' field can store data of any type (Mixed) since it's dynamic.
 * The 'type' field specifies the type of the 'value' field.
 */
const dynamicFieldSchema = new mongoose.Schema({
  key: {
    type: String,
  },
  value: {
    type: Schema.Types.Mixed,
  },
  type: {
    type: String,
    enum: Object.values(enumModel.EnumOfTypeOfValue),
  },
});

const DealSummarySchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    propertySummary: [dynamicFieldSchema],
    dealMetrics: [dynamicFieldSchema],
    financingRequest: [dynamicFieldSchema],
    sourcesAndUses: {
      sources: [dynamicFieldSchema],
      uses: [dynamicFieldSchema],
    },
    rentRollSummary: [[dynamicFieldSchema]],
    financialSummary: {
      revenue: [
        {
          key: String,
          stabilizedValue: String,
          inPlaceValue: String,
          stabilizedType: {
            type: String,
            enum: Object.values(enumModel.EnumOfTypeOfValue),
          },
          inPlaceType: {
            type: String,
            enum: Object.values(enumModel.EnumOfTypeOfValue),
          },
          // To store note for particular revenue field
          note: String,
        },
      ],
      expenses: [
        {
          key: String,
          stabilizedValue: String,
          inPlaceValue: String,
          stabilizedType: {
            type: String,
            enum: Object.values(enumModel.EnumOfTypeOfValue),
          },
          inPlaceType: {
            type: String,
            enum: Object.values(enumModel.EnumOfTypeOfValue),
          },
          // To store note for particular expenses field
          note: String,
        },
      ],
      netOperatingIncome: {
        stabilizedValue: String,
        inPlaceValue: String,
      },
    },
    deal: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Deal',
      required: true,
    },
    url: {
      type: String,
    },
    executiveSummary: {
      type: String,
    },
    dealHighLights: {
      type: [String],
    },
    marketSummary: {
      type: String,
    },
    sponserOverview: {
      type: String,
    },
    mainPhoto: {
      type: PhotosSchema,
    },
    otherPhotos: {
      type: [PhotosSchema],
    },
    // map has two fields : lat=latitude, lng=longitude
    map: {
      lat: {
        type: Number,
      },
      lng: {
        type: Number,
      },
    },
    documents: {
      type: [PhotosSchema],
    },
    dataSheet: {
      type: PhotosSchema,
    },
    dynamicField: [
      {
        name: String,
        type: {
          type: String,
          enum: Object.values(enumModel.EnumOfDynamicFieldType),
        },
        response: {
          bulletPoints: [String],
          text: String,
          fileUrl: String,
          fileName: String,
          /*
           * The 'tableData' array is a nested array structure, used to store the data of table type dynamicFields.
           * It contains an array of arrays where each inner array represents a row of data.
           * Each row is an array of objects with three properties: 'key', 'value', and 'type'.
           * tableData is imported from the url stored in fileUrl.
           */
          tableData: [[dynamicFieldSchema]],
        },
        // 'sectionName' property is a string representing the name of the section at below dynamicField added.
        sectionName: {
          type: String,
          enum: Object.values(enumModel.EnumOfSectionName),
        },
        // 'index' property is a number representing the index of the dynamic field from above section.
        // index is used to get the orders of the dynamic fields from the particular section , if same sectionName come then index will be increase by one.
        index: {
          type: Number,
        },
      },
    ],
    // this is used to indicate dealSummary is created along with deal or not.
    isDealSummaryAddedFromDeal: {
      type: Boolean,
      default: false,
    },
    // this is for the heading the presentation tab
    heading: headingSchema,
  },
  { timestamps: { createdAt: true, updatedAt: true }, autoCreate: true }
);

DealSummarySchema.plugin(toJSON);
DealSummarySchema.plugin(mongoosePaginateV2);
DealSummarySchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const DealSummaryModel = mongoose.models.DealSummary || mongoose.model('DealSummary', DealSummarySchema, 'DealSummary');
module.exports = DealSummaryModel;
