/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
const EnumCodeTypeOfCode = {
  RESETPASSWORD: 'resetPassword',
  LOGIN: 'login',
};
const EnumRoleOfUser = {
  USER: 'user',
  ADVISOR: 'advisor',
  LENDER: 'lender',
};
const EnumPlatformOfDeviceToken = {
  ANDROID: 'android',
  IOS: 'ios',
  WEB: 'web',
};
const EnumStageOfDeal = {
  INTAKE: 'intake',
  PREPARING_MATERIALS: 'preparingMaterials',
  OUT_IN_MARKET: 'outInMarket',
  SELECTING_QUOTES: 'selectingQuotes',
  CLOSING: 'closing',
  CLOSED: 'closed',
};
const EnumAssetTypeOfDeal = {
  MULTIFAMILY: 'multifamily',
  OFFICE: 'office',
  RETAIL: 'retail',
  INDUSTRIAL: 'industrial',
  HOSPITALITY: 'hospitality',
  RESIDENTIAL: 'residential',
  SELF_STORAGE: 'selfStorage',
  MOBILE_HOME_PARK: 'mobileHomePark',
  STUDENT_HOUSING: 'studentHousing',
  SPECIALTY: 'specialty',
};
const EnumLoanPurposeOfDeal = {
  PURCHASE: 'purchase',
  REFINANCE: 'refinance',
  CONSTRUCTION: 'construction',
};
const EnumLoanTypeOfDeal = {
  PERMANENT: 'permanent',
  TRANSITIONAL: 'transitional',
  CONSTRUCTION: 'construction',
  STABILIZED: 'Stabilized',
};
const EnumLenderProgramTypeOfLenderProgram = {
  CONSTRUCTION: 'construction',
  TRANSITIONAL: 'transitional',
  STABILIZED: 'stabilized',
  LAND: 'land',
};
const EnumLenderTypeOfLendingInstitution = {
  CREDIT_UNION: 'creditUnion',
  LOCAL_BANK: 'localBank',
  REGIONAL_BANK: 'regionalBank',
  CMBS: 'cmbs',
  AGENCY: 'agency',
  HUD: 'hud',
  LIFECO: 'lifeco',
  DEBT_FUND: 'debtFund',
  HARD_MONEY: 'hardMoney',
};
const EnumStageOfLenderPlacement = {
  NEW: 'new',
  SENT: 'sent',
  REVIEWING: 'reviewing',
  TERMS_RECEIVED: 'termsReceived',
  PASS: 'pass',
  TERMS_SHEET_RECEIVED: 'termsSheetReceived',
  CLOSING: 'closing',
  CLOSED: 'closed',
};
const EnumTermSheetOfLenderPlacement = {
  PDF: 'pdf',
  DOC: 'doc',
  DOCX: 'docx',
  PPT: 'ppt',
  XLS: 'xls',
  XLSX: 'xlsx',
  PPTX: 'pptx',
};
const EnumInterestRateTypeOfTerms = {
  FIXED_RATE: 'fixedRate',
  FLOATING_RATE: 'floatingRate',
};
const EnumEmailAttachmentsOfEmailTemplate = {
  PDF: 'pdf',
  DOC: 'doc',
  DOCX: 'docx',
  PPT: 'ppt',
  PPTX: 'pptx',
  XLS: 'xls',
  XLSX: 'xlsx',
};
const EnumTaskDocumentsOfTask = {
  PDF: 'pdf',
  DOC: 'doc',
  DOCX: 'docx',
  PPT: 'ppt',
  PPTX: 'pptx',
  XLS: 'xls',
  XLSX: 'xlsx',
};
const EnumDocumentTypeOfDealDocument = {
  PROPERTY_INFORMATION: 'propertyInformation',
  PROPERTY_FINANCIAL_INFORMATION: 'propertyFinancialInformation',
  SPONSER_INFORMATION: 'sponserInformation',
  OTHERS: 'others',
};
const EnumFileOfDealDocument = {
  PNG: 'png',
  JPG: 'jpg',
  PDF: 'pdf',
  DOC: 'doc',
  DOCX: 'docx',
  PPT: 'ppt',
  PPTX: 'pptx',
  XLS: 'xls',
  XLSX: 'xlsx',
};
const EnumContentType = {
  APLICATION_PDF: 'application/pdf',
  APLICATION_DOC: 'application/msword',
  APLICATION_DOCX: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  APLICATION_PPT: 'application/vnd.ms-powerpoint',
  APLICATION_XLS: 'application/vnd.ms-excel',
  APLICATION_XLSX: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  APLICATION_PPTX: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  IMAGE_PNG: 'image/png',
  IMAGE_JPEG: 'image/jpeg',
};
const EnumTypeOfToken = {
  RESET_PASSWORD: 'resetPassword',
  VERIFY_EMAIL: 'verifyEmail',
  REFRESH: 'refresh',
};
const EnumTypeOfStatus = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
};

module.exports = {
  EnumContentType,
  EnumCodeTypeOfCode,
  EnumRoleOfUser,
  EnumPlatformOfDeviceToken,
  EnumStageOfDeal,
  EnumAssetTypeOfDeal,
  EnumLoanPurposeOfDeal,
  EnumLoanTypeOfDeal,
  EnumLenderProgramTypeOfLenderProgram,
  EnumLenderTypeOfLendingInstitution,
  EnumStageOfLenderPlacement,
  EnumTermSheetOfLenderPlacement,
  EnumInterestRateTypeOfTerms,
  EnumEmailAttachmentsOfEmailTemplate,
  EnumTaskDocumentsOfTask,
  EnumDocumentTypeOfDealDocument,
  EnumFileOfDealDocument,
  EnumTypeOfToken,
  EnumTypeOfStatus,
};
