/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const FeedbackSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * Subject of Feedback
     * */
    subject: {
      type: String,
      required: true,
    },
    /**
     * Description of Feedback
     * */
    description: {
      type: String,
      required: true,
    },
    /**
     * Image for Feedback
     * */
    images: {
      type: [String],
    },
  },
  { timestamps: { createdAt: true, updatedAt: true }, autoCreate: true }
);
FeedbackSchema.plugin(toJSON);
FeedbackSchema.plugin(mongoosePaginateV2);
FeedbackSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const FeedbackModel = mongoose.models.Feedback || mongoose.model('Feedback', FeedbackSchema, 'Feedback');
module.exports = FeedbackModel;
