/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports = {
  termSheetOfLenderPlacement: {
    uploadServiceType: 'direct',
    allowedExtension: ['pdf', 'doc', 'docx', 'ppt', 'xls', 'xlsx', 'pptx'],
    allowedMaxFileSize: 10240,
    thumbnailResolutions: [],
    generateThumbnails: false,
  },
  emailAttachmentsOfEmailTemplate: {
    uploadServiceType: 'direct',
    allowedExtension: ['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx'],
    allowedMaxFileSize: 10240,
    thumbnailResolutions: [],
    generateThumbnails: false,
  },
  taskDocumentsOfTask: {
    uploadServiceType: 'direct',
    allowedExtension: ['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx'],
    allowedMaxFileSize: 10240,
    thumbnailResolutions: [],
    generateThumbnails: false,
  },
  fileOfDealdocument: {
    uploadServiceType: 'direct',
    allowedExtension: ['png', 'jpg', 'pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx'],
    allowedMaxFileSize: 30720,
    thumbnailResolutions: [],
    generateThumbnails: false,
  },
  fileOfDealSummary: {
    uploadServiceType: 'direct',
    allowedExtension: ['png', 'jpg', 'jpeg', 'pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx'],
    allowedMaxFileSize: 30720,
    thumbnailResolutions: [],
    generateThumbnails: false,
  },
};
