/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.User = require('./user.model');
module.exports.Deal = require('./deal.model');
module.exports.Invitation = require('./invitation.model');
module.exports.DealNotes = require('./dealNotes.model');
module.exports.LenderProgram = require('./lenderProgram.model');
module.exports.LendingInstitution = require('./lendingInstitution.model');
module.exports.LenderPlacement = require('./lenderPlacement.model');
module.exports.LenderContact = require('./lenderContact.model');
module.exports.LenderNotes = require('./lenderNotes.model');
module.exports.EmailTemplate = require('./emailTemplate.model');
module.exports.ActivityLog = require('./activityLog.model');
module.exports.Feedback = require('./feedback.model');
module.exports.BugReport = require('./bugReport.model');
module.exports.FAQ = require('./FAQ.model');
module.exports.LenderInstituteNotes = require('./lenderInstituteNotes.model');
module.exports.Task = require('./task.model');
module.exports.DealDocument = require('./dealDocument.model');
module.exports.Token = require('./token.model');
module.exports.FileFieldValidation = require('./fileFieldValidation.model');
module.exports.Rates = require('./rates.model');
module.exports.TempS3 = require('./tempS3.model');
module.exports.Error = require('./error.model');
module.exports.Enum = require('./enum.model');
module.exports.plugins = require('./plugins');
