/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';
import enumModel from './enum.model';

const InvitationSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    deal: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Deal',
    },
    invitee: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    invitedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    role: {
      type: String,
    },
    inviteeEmail: {
      type: String,
      // eslint-disable-next-line security/detect-unsafe-regex
      match: /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/,
    },
    status: {
      type: String,
      enum: Object.values(enumModel.EnumTypeOfStatus),
      required: true,
      default: enumModel.EnumTypeOfStatus.PENDING,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true }, autoCreate: true }
);
InvitationSchema.plugin(toJSON);
InvitationSchema.plugin(mongoosePaginateV2);
InvitationSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const InvitationModel = mongoose.models.Invitation || mongoose.model('Invitation', InvitationSchema, 'Invitation');
module.exports = InvitationModel;
