/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const RatesSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    name: {
      type: String,
    },
    current: {
      type: Number,
    },
    previous: {
      type: Number,
    },
    timestamp: {
      type: Date,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true }, autoCreate: true }
);
RatesSchema.plugin(toJSON);
RatesSchema.plugin(mongoosePaginateV2);
RatesSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});

// // Define the toJSON transform method for the DealNotesSchema options object
// RatesSchema.options.toJSON.transform = function (doc, { createdAt, ...ret }) {
//   if (createdAt) {
//     const timeDiff = Date.now() - createdAt.getTime();
//     if (timeDiff <= 24 * 60 * 60 * 1000) {
//       // Set isEnabled property to false
//       // eslint-disable-next-line no-param-reassign
//       ret.isEnabled = false;
//     }
//   }
//   // Return the ret object
//   return ret;
// };
const RatesModel = mongoose.models.Rates || mongoose.model('Rates', RatesSchema, 'Rates');
module.exports = RatesModel;
