/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON } from 'models/plugins';

const fileSchema = new mongoose.Schema(
  {
    url: {
      type: String,
      required: true,
    },
    fileName: {
      type: String,
    },
    fileType: {
      type: String,
    },
    fileDescription: {
      type: String,
    },
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);

const SponsorSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    name: {
      type: String,
    },
    borrowersEmails: {
      type: [String],
    },
    website: {
      type: String,
    },
    headquarter: {
      type: String,
    },
    description: {
      type: String,
    },
    photo: {
      type: fileSchema,
    },
    portfolio: {
      type: [mongoose.Schema.Types.Mixed],
    },
    documents: {
      type: [fileSchema],
    },
    advisor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    borrowers: {
      type: [mongoose.Schema.Types.ObjectId],
      ref: 'User',
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
SponsorSchema.plugin(toJSON);
SponsorSchema.plugin(mongoosePaginateV2);
const SponsorModel = mongoose.models.Sponser || mongoose.model('Sponsor', SponsorSchema, 'Sponsor');
module.exports = SponsorModel;
